name: Run Unicode Test Suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Clone text-rendering-tests repository
      run: |
        git clone --recursive https://github.com/unicode-org/text-rendering-tests.git

    - name: Run check.py script
      run: |
        cd text-rendering-tests
        python check.py --engine=OpenType.js --output="../reports/${{ GITHUB_SHA }}.html"
        if [[ "$PUSH_TO_MAIN" == "true" ]]; then
          # For pushes (merges to master)
          # Placeholder comment for later action
          echo "Generated HTML for merges to master. Commit logic will be added later."
        fi

    - name: Upload build artifact
      if: ${{ !env.PUSH_TO_MAIN }}
      uses: actions/upload-artifact@v2
      with:
        name: html-artifact
        path: ../reports/${{ GITHUB_SHA }}.html
