name: Run Unicode Test Suite

on:
  push:
    branches:
      - master
  pull_request:
  
permissions: 
   pull-requests: write 
   
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      SHORT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      ARTIFACT_URL: ''
      REPORT_FILE: ''
      REPORT_SUMMARY: ''

    steps:
     
    - name: Set environment variables
      run: |
        SHORT_COMMIT_SHA=$(echo "${{ env.COMMIT_SHA }}" | cut -c 1-7)
        echo "SHORT_COMMIT_SHA=$SHORT_COMMIT_SHA" >> $GITHUB_ENV
        echo "REPORT_FILE=reports/${{ env.COMMIT_SHA }}.html" >> $GITHUB_ENV
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4

    - run: npm install -D jsdom

    # - name: Setup ninja
    #   uses: seanmiddleditch/gha-setup-ninja@master

    - name: Clone text-rendering-tests repository
      run: |
        git clone https://github.com/unicode-org/text-rendering-tests.git

    - name: Ensure reports directory exists
      run: mkdir -p reports

    # for speeding up the workflow when debugging this action
    - name: Delete HTML files in testcases directory
      run: |
        find text-rendering-tests/testcases -name '*.html' -not -name 'index.html' -delete
      
    - name: Run check.py script
      run: |
        cd text-rendering-tests
        python check.py --engine=OpenType.js --output="../${{ env.REPORT_FILE }}"
        
    - name: Replace version with commit hash and link to PR commit
      run: |
        sed -i -E "s@OpenType\.js(\xC2\xA0| )[0-9.]+@<a href=\"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/commits/${{ env.COMMIT_SHA }}\">OpenType.js ${{ env.SHORT_COMMIT_SHA }}</a>@" reports/${{ env.COMMIT_SHA }}.html

    - name: parse passing/failing tests
      run:  |
        {
          echo 'REPORT_SUMMARY<<EOF'
          $(node .github/workflows/scripts/report-counter.js)
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Upload build artifact
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      uses: actions/upload-artifact@v3
      with:
        name: unicode-text-rendering-report_${{ env.SHORT_COMMIT_SHA }}
        path: ${{ env.REPORT_FILE }}
  
    - name: Get artifact link
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      run: |
        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts"
        echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

    - name: Add or update status report comment
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      uses: thollander/actions-comment-pull-request@v2.4.3
      with:
        message: |
          ℹ Automatic [Unicode test suite](https://github.comunicode-org/text-rendering-tests) report for commit ${{ env.SHORT_COMMIT_SHA}}:
          ${{ env.REPORT_SUMMARY }}
          [download report](${{ env.ARTIFACT_URL }})
        comment_tag: unicode_test_report
