name: Run Unicode Test Suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      SHORT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      GH_PAT: ${{ secrets.GH_PAT }}  # Personal Access Token with 'repo' and 'workflow' scope
      ARTIFACT_URL: ''

    steps:
     
    - name: Set SHORT_COMMIT_SHA environment variable
      run: |
        SHORT_COMMIT_SHA=$(echo "${{ env.COMMIT_SHA }}" | cut -c 1-7)
        echo "SHORT_COMMIT_SHA=$SHORT_COMMIT_SHA" >> $GITHUB_ENV
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4

    # - name: Setup ninja
    #   uses: seanmiddleditch/gha-setup-ninja@master

    - name: Clone text-rendering-tests repository
      run: |
        git clone https://github.com/unicode-org/text-rendering-tests.git

    - name: Ensure reports directory exists
      run: mkdir -p reports

    # for speeding up the workflow when debugging this action
    - name: Delete HTML files in testcases directory
      run: |
        find text-rendering-tests/testcases -name '*.html' -not -name 'index.html' -delete
      
    - name: Run check.py script
      run: |
        cd text-rendering-tests
        python check.py --engine=OpenType.js --output="../reports/${{ env.COMMIT_SHA }}.html"
        
    - name: Replace version with commit hash and link to PR commit
      run: |
        sed -i -E "s@OpenType\.js(\xC2\xA0| )[0-9.]+@<a href=\"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/commits/${{ env.COMMIT_SHA }}\">OpenType.js ${{ env.SHORT_COMMIT_SHA }}</a>@" reports/${{ env.COMMIT_SHA }}.html

    - name: Upload build artifact
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      uses: actions/upload-artifact@v3
      with:
        name: unicode-text-rendering-report_${{ env.SHORT_COMMIT_SHA }}
        path: reports/${{ env.COMMIT_SHA }}.html
  
    - name: Get artifact link
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      run: |
        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}"
        echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

    - name: Add or update status report comment
      if: ${{ env.PUSH_TO_MAIN == 'false' }}
      uses: thollander/actions-comment-pull-request@v2.4.3
      with:
        message: |
          Hello world ! :wave:
          ${{ env.ARTIFACT_URL }}
        reactions: eyes, rocket
      
